name: Laravel FMS - Lokal
values:
  - key: base_url
    value: 'http://127.0.0.1:8088'
  - key: csrf_token
    value: ''
  - key: admin_email
    value: admin@example.com
  - key: admin_password
    value: password
  - key: run_id
    value: ''
  - key: department_name
    value: ''
  - key: folder_name
    value: ''
  - key: document_title
    value: ''
